# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  terraformVersion: '1.16.1'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  serviceConnection: 'Azure-Service-Connection'

stages:
  - stage: Terraform_build_stage
    displayName: Terraform_build_stage
    jobs:
      - job: 
        displayName: Terraform_build_ob
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'devtoazure'
              backendAzureRmResourceGroupName: 'Terraform_build-stage'
              backendAzureRmStorageAccountName: 'azstrgbackend'
              backendAzureRmContainerName: 'backendcontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out=$(Build.ArtifactStagingDirectory)/tfplan'
              environmentServiceNameAzureRM: 'devtoazure'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/tfplan'
              artifact: 'terraform-plan'
              publishLocation: 'pipeline'

  - stage: 
    displayName: Terraform_deploy_stage
    dependsOn: Terraform_build_stage
    condition: succeeded()
    jobs:
      - deployment: Terraform_deploy_job
        displayName: Terraform_deploy_job
        environment: terraform-production
        strategy:
         runOnce:
           deploy:
             steps:
               - task: TerraformInstaller@1
                 inputs:
                   terraformVersion: 'latest'

               - task: DownloadPipelineArtifact@2
                 inputs:
                   buildType: 'current'
                   targetPath: '$(Pipeline.Workspace)'

               - task: TerraformTask@5
                 inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: 'devtoazure'
                  backendAzureRmResourceGroupName: 'Terraform_build-stage'
                  backendAzureRmStorageAccountName: 'azstrgbackend'
                  backendAzureRmContainerName: 'backendcontainer'
                  backendAzureRmKey: 'terraform.tfstate'

               - task: TerraformTask@5
                 inputs:
                   provider: 'azurerm'
                   command: 'apply'
                   commandOptions: '$(Pipeline.Workspace)/terraform-plan/tfplan'
                   environmentServiceNameAzureRM: 'devtoazure'
                   
              

                
         
